In [20]:
import numpy as np
from rbm import  visibleToHiddenVec, hiddenToVisible

In [21]:
d_v = 16

d_h = 8

k = 5

In [22]:
test_v = np.concatenate(
    [np.eye(k, k) for _ in range(d_v // k)] + [np.eye(k, k)[:d_v % k]],
    axis=0
)

test_v 

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.],
       [1., 0., 0., 0., 0.]])

In [23]:
test_h = np.random.binomial(1, .5, d_h)

test_h

array([0, 0, 0, 1, 1, 1, 1, 1])

In [24]:
test_w = np.random.rand(d_v, d_h, k)

test_w.shape

(16, 8, 5)

In [25]:
visibleToHiddenVec(test_v, test_w)

array([0.99990415, 0.9997174 , 0.99977217, 0.99887106, 0.999607  ,
       0.99974973, 0.99874149, 0.99993232])

In [26]:
hiddenToVisible(test_h, test_w)

array([[0.07552013, 0.24591318, 0.28586845, 0.19633729, 0.19636095],
       [0.07271549, 0.44253242, 0.13592133, 0.29795449, 0.05087627],
       [0.21979391, 0.2456276 , 0.13877556, 0.06015563, 0.33564731],
       [0.13017642, 0.22161792, 0.11487526, 0.17293019, 0.36040021],
       [0.31118355, 0.1371315 , 0.1617828 , 0.10701421, 0.28288793],
       [0.21692043, 0.24002358, 0.12360856, 0.19450672, 0.22494072],
       [0.40604386, 0.11754117, 0.17520877, 0.17002414, 0.13118206],
       [0.25470337, 0.57635434, 0.06080839, 0.08169148, 0.02644242],
       [0.21842235, 0.11025736, 0.05720797, 0.28783793, 0.32627439],
       [0.22268197, 0.19298969, 0.10140522, 0.25269769, 0.23022542],
       [0.25805495, 0.14065578, 0.13687637, 0.28696955, 0.17744336],
       [0.19830339, 0.11179176, 0.13400331, 0.27142057, 0.28448097],
       [0.14087141, 0.37212727, 0.07333559, 0.09207474, 0.32159099],
       [0.27333517, 0.1767007 , 0.35452836, 0.14960655, 0.04582923],
       [0.28942485, 0.19237235, 0.